services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file:
      - docker/postgres/.env
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    build:
      context: docker/pgadmin
    env_file:
      - docker/pgadmin/.env
    ports:
      - "5050:80"
    restart: always