services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file:
      - docker/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin
    build:
      context: docker/pgadmin
    env_file:
      - docker/pgadmin/.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin
    restart: always

volumes:
  postgres:
  pgadmin4: